#!/bin/bash
xclip -o |cat > /tmp/clip.temp
while read r; do
echo $r
echo $r|espeak -v f2 -w /tmp/xclipline.wav -s 130
play /tmp/xclipline.wav echos 0.4 0.88 10 0.4 treble 1  2>/dev/null
done </tmp/clip.temp
